### ISSUE TITLE
Can we create the same code with keras or tensorflow??

### ISSUE THREAD

**Issue by sukantdeb** [drewserles/GenerationQ#1]
Hi I was just going through the code and found very efficient.. Really appreciate your efforts..
As i am also an beginner in RNN. Can you please let me know if we can make the code in Keras or tensorflow instead of pytorch?

**Comment by drewserles** [comment]
Hi Sukantdeb, glad to hear it. OpenNMT has a Tensorflow implementation you could modify if you're interested: https://github.com/OpenNMT/OpenNMT-tf
